name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build (and publish) main image
        env:
          # fork friendly ^^
          DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/caddy-trojan
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ steps.prepare.outputs.tag_name }} \
            --push \
            -t ${DOCKER_REPO}:${{ steps.prepare.outputs.tag_name }} \
            -f dockerfiles/endpoints-operator/Dockerfile \
            .
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=latest \
            --push \
            -t ${DOCKER_REPO}:latest \
            -f dockerfiles/endpoints-operator/Dockerfile \
            .
